safe:    false
auto:    false
server:  false
baseurl: /

source:      .
destination: ./_site
plugins:     ./_plugins

permalink:  pretty
pygments:   true
lsi:        false
paginate:   5

ga_id:      UA-37375728-1
